#+STARTUP: overview
#+TITLE: MyEmacs
#+CREATOR: Abhishek Anand Amralkar
#+LANGUAGE: en
#+OPTIONS: num:nil
#+ATTR_HTML: :style margin-left: auto; margin-right: auto;
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Installation

git clone https://github.com/abhishekamralkar/Myemacs-org-bable ~/.emacs.d

To use you should remove your own ~/.emacs and your ~/.emacs.d prior to cloning this configuration. 

* About Me

#+begin_src emacs-lisp
(setq user-full-name "Abhishek Anand Amralkar"
      user-mail-address "abhishekamralkar@gmail.com")
#+end_src

* Use-Package

The use-package macro allows you to isolate package configuration in your .emacs file in a way that is both performance-oriented and, well, tidy. 

#+begin_src emacs-lisp
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org"   . "https://orgmode.org/elpa/")
                         ("elpa"  . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
(package-refresh-contents))

;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
(package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
(require 'org-tempo)
#+end_src

* Auto Tangle

Hook to generate the .el file from .org file on save

#+begin_src emacs-lisp
(add-hook 'org-mode-hook
          (lambda () (add-hook 'after-save-hook #'org-babel-tangle
                          :append :local)))
#+end_src

* Theme

Using Doom Emacs theme 

#+begin_src emacs-lisp
(use-package doom-themes
  :init (load-theme 'doom-palenight t))
#+end_src

* Fonts

Fira-Code no doubt one of the best fonts with better presicions

#+begin_src emacs-lisp
(font-family-list)
(add-to-list 'default-frame-alist
     (cond
         ((string-equal system-type "darwin")    '(font . "Fira Code-12"))
         ((string-equal system-type "gnu/linux") '(font . "Fira Code-10"))))

(use-package ac-emoji
  :ensure t)

(set-fontset-font
  t 'symbol
(font-spec :family "Symbola") nil 'prepend)
#+end_src

* Emacs UI

** No Startup Screen

#+begin_src emacs-lisp
(setq inhibit-startup-message t)
#+end_src

** No Toolbar

#+begin_src emacs-lisp 
(tool-bar-mode -1)
#+end_src

** No Menubar

#+begin_src emacs-lisp 
(menu-bar-mode -1)
#+end_src

** No Scrollbar

#+begin_src emacs-lisp 
(scroll-bar-mode -1)
#+end_src

** No Ringing Bells

#+begin_src emacs-lisp
(setq ring-bell-function 'ignore)  
#+end_src

** UTF-8 Encoding

#+begin_src emacs-lisp
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)   
#+end_src

** No backup please!

#+begin_src emacs-lisp
(setq make-backup-files nil)
(setq auto-save-default nil)   
#+end_src

** y for yes and n for no

#+begin_src emacs-lisp 
(defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

** Dashboard

#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :config
    (dashboard-setup-startup-hook))
#+end_src

#+begin_src emacs-lisp
;; Set the title
(setq dashboard-banner-logo-title "Welcome to AAA Emacs Dashboard")

;; Content is not centered by default. To center, set
(setq dashboard-center-content t)

;; To disable shortcut "jump" indicators for each section, set
(setq dashboard-show-shortcuts nil)

(setq dashboard-items '((recents  . 5)
                        (bookmarks . 5)
                        (projects . 5)
                        (agenda . 5)
                        (registers . 5)))
#+end_src

** Modeline

With modeline we can enhance the Emacs look and feel. Spacemacs spaceline is awesome. I tried spaceline but doom-modeline is best. This package is able to display icons if all-the-icons package and required fonts are installed. Run M-x all-the-icons-install-fonts to install the necessary fonts. Please refer to the installation guide.

#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))
#+end_src

#+begin_src emacs-lisp
(use-package all-the-icons
  :ensure t)
#+end_src

** No Separator

#+begin_src emacs-lisp
(setq powerline-default-separator nil)   
#+end_src

** Cursor Position

Show the current line and column for your cursor.

#+begin_src emacs-lisp
(setq line-number-mode t)
(setq column-number-mode t)   
#+end_src

** Clock

#+begin_src emacs-lisp
(setq display-time-24hr-format t)
(setq display-time-format "%H:%M - %d %B %Y")
(display-time-mode 1)
#+end_src

** Battery

#+begin_src emacs-lisp
(use-package fancy-battery
  :ensure t
  :config
    (setq fancy-battery-show-percentage t)
    (setq battery-update-interval 15)
    (if window-system
      (fancy-battery-mode)
      (display-battery-mode)))   
#+end_src
