name: Emacs CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y emacs-nox git wget unzip

    - name: Install Fonts (FiraCode Nerd Font)
      run: |
        mkdir -p ~/.local/share/fonts
        cd ~/.local/share/fonts
        wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
        unzip -o FiraCode.zip
        fc-cache -fv

    - name: Tangle Org File
      run: |
        emacs --batch --eval "(progn (find-file \"./emacs.org\") (org-babel-tangle) (kill-emacs))"

    - name: Test Emacs Configuration
      run: |
        emacs --batch -l ./init.el --eval "(message \"Emacs configuration loaded successfully!\")"

    - name: Run Tests (Optional)
      run: |
        # Add your test commands here if you have tests
        echo "No tests defined yet."